name: Run tests across emacs versions
on: [push, pull_request]
jobs:
  test-emacs-versions:
    strategy:
      matrix:
        emacs-version: [28, 29]
    runs-on: ubuntu-latest
    container: silex/emacs:${{matrix.emacs-version}}-ci-eask
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install test dependencies
        run: eask install-deps --dev
      - name: Run tests
        run: eask run script test
